### ISSUE TITLE
Style fix spacer two

### ISSUE THREAD

**Issue by MeghanHughes** [ManuInnovations/trustProject#28]
The broken up paragraphs in spacer two snuck into the new master. (Big long lawyer's quote)
I have removed the delay fade-ins for each separate paragraph but unsure how to style to breaks. It has a p class already ``p class="lead wow fadeIn">`` but I can't find it in any of the style files in order to change it. 
Don't know if this is a case for ``<br />`` or something else?

**Comment by janie-t** [comment]
What exactly do you want the quote to look like?  Sorry I did the paragraphs - I thought that was what it was like before, but do you want just one big paragraph?
